# Generated by Django 4.2.6 on 2024-07-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0030_project_proj_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Super User', 'Super User'), ('Manager', 'Manager'), ('Team Lead', 'Team Lead')], default='User', max_length=50),
        ),
    ]
