# Generated by Django 4.2.6 on 2024-07-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0032_remove_userprofile_intials_remove_userprofile_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='proficiency',
        ),
    ]
