# Generated by Django 4.2.6 on 2024-07-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0036_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_wallet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
