# Generated by Django 4.2.6 on 2024-07-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0037_task_task_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
