# Generated by Django 4.2.6 on 2024-07-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0039_alter_userprofile_wallet_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(choices=[('User', 'User'), ('Manager', 'Manager'), ('Team Lead', 'Team Lead')], default='User', max_length=50),
        ),
    ]
