# Generated by Django 4.2.6 on 2024-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0040_alter_userprofile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='proficiency',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Basic', max_length=50, null=True),
        ),
    ]
