# Generated by Django 4.2.6 on 2024-07-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0041_userprofile_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_flaged',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
