# Generated by Django 4.2.6 on 2024-07-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0042_task_is_flaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ETA',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
