# Generated by Django 4.2.6 on 2024-07-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0043_task_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approvals',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
