# Generated by Django 4.2.6 on 2024-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0046_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer ', 'Backend Developer'), ('Full Stack Developer ', 'Full Stack Developer'), ('Cloud Developer ', 'Cloud Developer')], max_length=50, null=True),
        ),
    ]
