# Generated by Django 4.2.6 on 2024-08-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0049_alter_message_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='flagged'),
        ),
    ]
